<?php

return [
    (object)[
        'id' => 1,
        'channel_name' => '原创小说',
        'channel_explanation' => '原创小说板块从此进入',
        'order_by' => '1',
        'type' => 'book',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 2,
        'channel_name' => '同人衍生',
        'channel_explanation' => '同人衍生板块从此进入',
        'order_by' => '2',
        'type' => 'book',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 3,
        'channel_name' => '作业专区',
        'channel_explanation' => '站内作业板块从此进入',
        'order_by' => '3',
        'is_public' => false,
        'type' => 'homework',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => false,
        'is_public' => false,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 4,
        'channel_name' => '读写交流',
        'channel_explanation' => '读写交流板块从此进入',
        'order_by' => '4',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 5,
        'channel_name' => '日常闲聊',
        'channel_explanation' => '闲谈、吐槽、求助、八卦、安利',
        'order_by' => '5',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 6,
        'channel_name' => '随笔',
        'channel_explanation' => '随笔板块从此进入',
        'order_by' => '6',
        'type' => 'column',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 7,
        'channel_name' => '站务管理',
        'channel_explanation' => '站务管理板块从此进入',
        'order_by' => '9',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => false,
        'allow_deletion' => false,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 8,
        'channel_name' => '违规举报',
        'channel_explanation' => '违规举报板块从此进入',
        'order_by' => '10',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => false,
        'allow_deletion' => false,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 9,
        'channel_name' => '投诉仲裁',
        'channel_explanation' => '投诉仲裁板块从此进入',
        'order_by' => '11',
        'type' => 'thread',
        'allow_anonymous' => false,
        'allow_edit' => false,
        'allow_deletion' => false,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 10,
        'channel_name' => '后台管理',
        'channel_explanation' => '后台管理板块从此进入',
        'order_by' => '12',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => false,
        'is_public' => false,
        'show_on_homepage' => false,
    ],
    (object)[
        'id' => 11,
        'channel_name' => '档案',
        'channel_explanation' => '档案板块从此进入',
        'order_by' => '13',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => false,
        'is_public' => false,
        'show_on_homepage' => false,
    ],
    (object)[
        'id' => 12,
        'channel_name' => '后花园',
        'channel_explanation' => '后花园从此进入',
        'order_by' => '14',
        'type' => 'thread',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => false,
        'is_public' => false,
        'show_on_homepage' => false,
    ],
    (object)[
        'id' => 13,
        'channel_name' => '清单',
        'channel_explanation' => '书单板块从此进入',
        'order_by' => '7',
        'type' => 'list',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
    (object)[
        'id' => 14,
        'channel_name' => '问题箱',
        'channel_explanation' => '书单板块从此进入',
        'order_by' => '8',
        'type' => 'box',
        'allow_anonymous' => true,
        'allow_edit' => true,
        'allow_deletion' => true,
        'is_public' => true,
        'show_on_homepage' => true,
    ],
];
